config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  authenticated :user do
    root to: "authorized_dashboard#show", as: :authenticated_root
  end

  scope 'hired' do
    get 'challenge', to: 'challenges#new', as: 'new_challenge'
    post 'challenges', to: 'challenges#create', as: 'challenges'
    get 'challenges/:id', to: 'challenges#edit', as: 'challenge'

    post 'gql', to: 'challenges/registrations#create'
    get 'challenge/report/:id', to: 'challenges/reports#show', as: 'report'
  end

  root to: "dashboard#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge
  include ActiveModel::Model

  Attributes = %i{id completed_at invited_at points results_url score score_card started_at
    time_taken token url}

  attr_accessor *Attributes

  def to_json
    <<~JSON.squish
    {
      "monotonic_event_id": "#{id || token}",
      "datetime_completed": "#{completed_at}",
      "datetime_invited": "#{invited_at}",
      "datetime_started": "#{started_at}",
      "results_url": "#{results_url}",
      "score_card": {#{score_card_json}
        "points": #{points || 0},
        "score": #{score || 0}
      },
      "status": "#{status}",
      "time_taken_seconds": #{time_taken}
    }
    JSON
  end

  def status
    case
    when completed_at.present?
      'needs_review'
    when started_at.present?
      'started'
    when invited_at.present?
      'invited'
    end
  end

  def score_card
    @score_card ||= {}
  end

  def score_card_json
    return '' if score_card.empty?

    <<~JSON.squish
      \n#{JSON.generate(score_card)},
    JSON
  end

  def score
    @score ||= 0
  end

  def points
    @points ||= 0
  end

  def sample_score_card
    <<~JSON.squish
    {
      "coding": {
        "points": 250,
        "questions": [{
            "points": 50,
            "score": 0,
            "template_id": 57,
            "time_taken": 4.887827157974243
          },
          {
            "points": 50,
            "score": 0,
            "template_id": 58,
            "time_taken": 0
          },
          {
            "points": 50,
            "score": 0,
            "template_id": 59,
            "time_taken": 0
          },
          {
            "points": 50,
            "score": 0,
            "template_id": 60,
            "time_taken": 0
          },
          {
            "points": 50,
            "score": 0,
            "template_id": 61,
            "time_taken": 0
          }
        ],
        "score": 0
      },
      "multiple_choice": {
        "points": 40,
        "questions": [{
            "points": 10,
            "score": 0,
            "template_id": 86
          },
          {
            "points": 10,
            "score": 0,
            "template_id": 82
          },
          {
            "points": 10,
            "score": 0,
            "template_id": 92
          },
          {
            "points": 10,
            "score": 0,
            "template_id": 94
          }
        ],
        "score": 0
      }
    }
    JSON
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authorized_controller.rb
class AuthorizedController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/authorized_dashboard_controller.rb
class AuthorizedDashboardController < AuthorizedController
  # GET /dashboard
  def show
  end
end

app/controllers/challenges/registrations_controller.rb
module Challenges; class RegistrationsController < ActionController::API
  before_action :authenticate_user!

  def create
    render json: {
      data: {
        sendHiredChallenge: {
          link: challenge_link,
          pk: challenge_id
        }
      }
    }
  end

  private

  def challenge_id
    @_challenge_id ||= Time.current.to_i
  end

  def challenge_link
    Rails.logger.info { "\n\n\nROOT_URL: #{root_url}" }
    hired_assessment_url = URI(root_url)

    Rails.application.routes.url_helpers.challenge_url(challenge_id, host: hired_assessment_url.to_s, token: token)
  end

  # this is a different shape than the actual assessment token that is passed,
  # but we're gonna use it so that we don't have to keep anything in memory.
  def token
    JWT.encode jwt_payload, nil, 'none'
  end

  private

  def authenticate_user!
    unless request.env['HTTP_AUTHORIZATION'].match(/hiredinteraltestkey1234567890abcd/i)
      raise AuthorizationError
    end
  end

  def jwt_payload
    { id: challenge_id }.merge(params['variables'].permit!)
  end
end; end

app/controllers/challenges/reports_controller.rb
module Challenges; class ReportsController < AuthorizedController
  # GET /challenge
  def show
    @challenge = Challenge.new(challenge_payload)
  end

  private

  def challenge_payload
    @_challenge_payload ||= payload.transform_keys(&:to_sym).slice(*Challenge::Attributes)
  end

  def payload
    @_payload ||= {}
    # begin
    #   decoded_token = JWT.decode params[:token], nil, false
    #   decoded_token.first
    # end
  end

  def hired_return_url
    redirect_url = URI(Rails.configuration.hired['url'])
    redirect_url.path = '/assessments'
    redirect_url
  end

  def challenge_params
    params.fetch(:challenge, {}).permit(*Challenge::Attributes)
  end
end; end

app/controllers/challenges_controller.rb
class ChallengesController < AuthorizedController
  # GET /challenge
  def new
    @challenge = Challenge.new(challenge_payload)

    render :edit
  end

  def create
    @challenge = Challenge.new(challenge_params)

    AttemptWebhookJob.perform_later(@challenge.to_json)

    redirect_to hired_return_url.to_s, status: :found
  end

  def edit
    @challenge = Challenge.new(challenge_payload)
  end

  private

  def challenge_payload
    @_challenge_payload ||= payload.transform_keys(&:to_sym).slice(*Challenge::Attributes)
  end

  def decoded_token
    JWT.decode params[:token], nil, false
  end

  def payload
    @_payload ||= decoded_token.first
  end

  def hired_return_url
    redirect_url = URI(Rails.configuration.hired['url'])
    redirect_url.path = '/assessments'
    redirect_url
  end

  def challenge_params
    params.fetch(:challenge, {}).permit(*Challenge::Attributes)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  # GET /dashboard
  def show
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def hired
    if current_omniauth_user
      sign_in_and_redirect current_omniauth_user
    else
      session["devise.hired_data"] = omniauth_provider_user_data
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

  private

  def current_omniauth_user
    @_current_omniauth_user ||= begin
      User.find_or_create_by(provider: omniauth_provider_user_data.provider, uid: omniauth_provider_user_data.uid) do |new_user|
        new_user.email = omniauth_provider_user_data.info['email']
        new_user.name = omniauth_provider_user_data.info['name']
        new_user.password = Devise.friendly_token[0, 20]
      end
    end
  end

  def omniauth_provider_user_data
    @_omniauth_provider_user_data ||= request.env["omniauth.auth"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_link
    link_to 'Login', new_user_session_path
  end

  def logout_link
    link_to 'Logout', destroy_user_session_path, method: 'delete'
  end
end

app/views/authorized_dashboard/show.html.erb
<div><%= logout_link %></div>

</br>
<div>Authenticated by Hired.com</div>
<div><%= "Name: #{current_user.name}" %></div>
<div><%= "Email: #{current_user.email}" %></div>

app/views/challenges/edit.html.erb
<h4>Challenge Result Mocker</h4>
<p>
  The webhook will save whatever this payload is, with the exception of the timestamp fields.

  For an examples of expected payloads check out the specs
</p>

<%= form_for @challenge do |f| %>
  <h3>Form contents</h3>
  <div>
    <%= f.label :id %>
    <%= f.text_field :id, value: @challenge.id %>
    <!-- <span>default: <%= @challenge.id %></span> -->
  <div>
  <div>
    <%= f.label :completed_at %>
    <%= f.text_field :completed_at %>
    <!-- <span>default: <%= @challenge.completed_at || 'NULL' %></span> -->
  <div>
  <div>
    <%= f.label :invited_at %>
    <%= f.text_field :invited_at %>
    <!-- <span>default: <%= @challenge.invited_at || 'NULL' %></span> -->
  <div>
  <div>
    <%= f.label :started_at %>
    <%= f.text_field :started_at %>
    <!-- <span>default: <%= @challenge.started_at || 'NULL' %></span> -->
  <div>
  <div>
    <%= f.label :results_url %>
    <%= f.text_field :results_url %>
    <!-- <span>default: <%= @challenge.results_url || 'NULL' %></span> -->
  <div>
  <div>
    <%= f.label :time_taken %>
    <%= f.text_field :time_taken %>
    <!-- <span>default: <%= @challenge.time_taken || 'NULL' %></span> -->
  <div>
  <div>
    <%= f.label :score %>
    <%= f.text_field :score %>
    <!-- <span>default: <%= @challenge.score %></span> -->
  <div>
  <div>
    <%= f.label :points %>
    <%= f.text_field :points %>
    <!-- <span>default: <%= @challenge.points %></span> -->
  <div>
  <div>
    <%= f.label :score_card %>
    <%= f.text_area :score_card %>
    <!-- <span>default: <%= @challenge.score_card || 'NULL' %></span> -->
  <div>
  <div>
    <%= f.submit "Finish Challenge" %>
  </div>
<% end %>

app/views/challenges/new.html.erb
<h4>Challenge Result Mocker</h4>
<p>
  The webhook will save whatever this payload is, with the exception of the timestamp fields.

  For an examples of expected payloads check out the specs
</p>

<%= form_for @challenge do |f| %>
  <h3>Form contents</h3>
  <div>
    <%= f.label :id %>
    <%= f.text_field :id, value: @challenge.id %>
    <!-- <span>default: <%= @challenge.id %></span> -->
  <div>
  <div>
    <%= f.label :completed_at %>
    <%= f.text_field :completed_at %>
    <!-- <span>default: <%= @challenge.completed_at || 'NULL' %></span> -->
  <div>
  <div>
    <%= f.label :invited_at %>
    <%= f.text_field :invited_at %>
    <!-- <span>default: <%= @challenge.invited_at || 'NULL' %></span> -->
  <div>
  <div>
    <%= f.label :started_at %>
    <%= f.text_field :started_at %>
    <!-- <span>default: <%= @challenge.started_at || 'NULL' %></span> -->
  <div>
  <div>
    <%= f.label :results_url %>
    <%= f.text_field :results_url %>
    <!-- <span>default: <%= @challenge.results_url || 'NULL' %></span> -->
  <div>
  <div>
    <%= f.label :time_taken %>
    <%= f.text_field :time_taken %>
    <!-- <span>default: <%= @challenge.time_taken || 'NULL' %></span> -->
  <div>
  <div>
    <%= f.label :score %>
    <%= f.text_field :score %>
    <!-- <span>default: <%= @challenge.score %></span> -->
  <div>
  <div>
    <%= f.label :points %>
    <%= f.text_field :points %>
    <!-- <span>default: <%= @challenge.points %></span> -->
  <div>
  <div>
    <%= f.label :score_card %>
    <%= f.text_area :score_card %>
    <!-- <span>default: <%= @challenge.score_card || 'NULL' %></span> -->
  <div>
  <div>
    <%= f.submit "Finish Challenge" %>
  </div>
<% end %>

app/views/dashboard/show.html.erb
<div>We don't have a clue who you are.</div>

<%= link_to "Sign in with #{OmniAuth::Utils.camelize('hired')}", omniauth_authorize_path('user', 'hired') %><br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <h1>Mock Hired Assesments</h1>

    <%= yield %>
  </body>
</html>